# Datasource configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.devservices.enabled=true

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# HTTP port
quarkus.http.port=8081

# Swagger / OpenAPI
quarkus.smallrye-openapi.info-title=Payment Service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API de gerenciamento de pagamentos
quarkus.swagger-ui.always-include=true